# Generated by Django 3.2.4 on 2021-08-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210830_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='headshot',
        ),
        migrations.AddField(
            model_name='book',
            name='headshot',
            field=models.ImageField(default=None, upload_to='author_headshots'),
            preserve_default=False,
        ),
    ]
