# Generated by Django 3.2.4 on 2021-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
