# Generated by Django 3.2.4 on 2021-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210830_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='headshot',
            field=models.ImageField(upload_to='book_headshots'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='search.Publisher'),
        ),
    ]
