# Generated by Django 3.2.4 on 2021-09-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210905_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
